### ISSUE TITLE
Scrape or convert 2000 county-level Democratic presidential primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#12]
County-level data only, HTML table [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/DemPres03072000.aspx). Things to know:

* Output file is named  `20000307__oh__democratic__primary__president.csv`
* Presidential results tallied by congressional district - use the district number in the results and create rows for each combination of district and county.
* Headers should be: county, candidate, party, office, district, votes. Use `President` as office.
* Only include candidate totals, don't include overall totals.

**Comment by palewire** [comment]
I'll try this one too while I'm at it.
