### ISSUE TITLE
Scrape or convert 2000 county-level Republican presidential primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#13]
Separate files for 
[Congressional district-level data] (http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/RepPres03072000.aspx) and [county-level](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/RepPresAt-Large03072000.aspx). You should put them into a single file. Things to know:

* Output file is named  `20000307__oh__republican__primary__president.csv`
* For Presidential results tallied by congressional district, create a row for each combination of district and county.
* Headers should be: county, candidate, party, office, district, votes. Use `President` as office.
* Only include candidate totals, don't include overall totals.

**Comment by palewire** [comment]
I'm going to try this one.

**Comment by dwillis** [comment]
The congressional district-level file looks great. If you're able to add the county-level file, too, that would be great. Some of the results will be identical with the exception of district, but others will not be.

**Comment by palewire** [comment]
do I give it a different file name?

**Comment by dwillis** [comment]
You can add to the same file if you pull from master.

**Comment by palewire** [comment]
So append the county totals to the bottom and leave district field null?

**Comment by dwillis** [comment]
Yep.
