### ISSUE TITLE
Scrape or convert 2000 county-level Republican Ohio House primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#19]
HTML table [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/RepOhHouseReps03072000.aspx). Things to know:

* Output file is named  `20000307__oh__republican__primary__state_house.csv`
* Results tallied by legislative district - use the district number in the results and create rows for each combination of district and county.
* Headers should be: county, candidate, party, office, district, votes. Use `State House` as office.
* Only include candidate totals, don't include overall totals. You can omit precinct reporting percentage.

**Comment by rdmurphy** [comment]
Grabbing this one.
