### ISSUE TITLE
Scrapers or data entry for Nov. 6, 2007, special primary elections for U.S. House

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#2]
County-level data only, HTML tables for [Democrats](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2007ElectionsResults/07-1106demFifthCong.aspx) and [Republicans](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2007ElectionsResults/07-1106repFifthCong.aspx). Both can be placed in a single file or separate files; it's up to you. Things to know:

* Output file is named `20111106__oh__special__primary__house__5.csv` (if one file), or `20111106__oh__democratic__special__primary__house__5.csv` and `20111106__oh__republican__special__primary__house__5.csv` for party-specific files.
* Headers should be: county, candidate, party, office, district, votes, pct. Use `U.S. House` as office.
* Only include candidate totals, don't include county totals.

**Comment by bsweger** [comment]
I'll try my hand at this one.
