### ISSUE TITLE
Scraper or data entry for Nov. 18, 2008 U.S. House special general election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#3]
County-level data only, HTML table is [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2008ElectionResults/USRep_111808.aspx). Things to know:

* Output file is named `20081118__oh__special__general__house__11.csv`
* Headers should be: county, candidate, party, office, district, votes, pct. Use `U.S. House` as office.
* Only include candidate totals, don't include county totals.

**Comment by ursulakaczmarek** [comment]
sending finished .csv via gmail
