### ISSUE TITLE
Scraper or data entry for July 13, 2010, special primary election for U.S. House

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#4]
County-level data only, HTML table [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2010results/20100713USRep-D.aspx). Things to know:

* Output file is named  `20100713__oh__democratic__special__primary__house__3.csv`
* Headers should be: county, candidate, party, office, district, votes, pct. Use `U.S. House` as office.
* Only include candidate totals, don't include county totals.

**Comment by ursulakaczmarek** [comment]
sending finished .csv via gmail
