### ISSUE TITLE
Scrape 2002 general election results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#44]
Using HTML tables [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2002Results.aspx), create a single CSV file containing results for the following offices: Governor/Lt Gov, Attorney General, Auditor, Secy of State, Treasurer, US Representative, State Senate, State Representative.

- Output file is named `20021105__oh__general.csv`
- Headers should be: county, candidate, party, office, district, votes, pct. Leave `district` empty for all but US Rep, State Senate and State Rep offices.

**Comment by christopherjenness** [comment]
I can get started on this.

**Comment by christopherjenness** [comment]
What is column "pct"?  Percent? If so, percent of what, exactly?

**Comment by dwillis** [comment]
Usually it's percent of total, but it is an optional field in any case.
