### ISSUE TITLE
Parse 2004 primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#46]
From HTML files here: https://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2004ElectionsResults.aspx 

These will be county-level files only, so combine all primary files into a single CSV named `20040302__oh__primary.csv` and include the following offices:

* President
* U.S. Senate
* U.S. House
* State Senate
* State House

**Comment by christopherjenness** [comment]
I'll start in this.

**Comment by christopherjenness** [comment]
For some reason, I can only find even-numbered districts for state senate: https://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2004ElectionsResults/04-1102OHSenate.aspx

Why is this?

**Comment by dwillis** [comment]
@christopherjenness pretty sure that state senate districts aren't all up for election at the same time.

**Comment by christopherjenness** [comment]
I see, thanks!
