### ISSUE TITLE
Convert 2012 General and Primary precinct results to CSV

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#48]
From the original Excel files here: https://www.sos.state.oh.us/elections/Research/electResultsMain/2012Results.aspx

There are some Python scripts in this repository that can help with that conversion.

**Comment by christopherjenness** [comment]
I'll get started on this.

**Comment by christopherjenness** [comment]
The [2012 directory](https://github.com/openelections/openelections-data-oh/tree/master/2012) already has general results.  Specifically, which files need to be created?

**Comment by dwillis** [comment]
The precinct-level results.
