### ISSUE TITLE
County and precinct-level results for 2006 elections

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#54]
Scrape the HTML tables posted at https://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2006ElectionsResults.aspx for both the general and primary elections for the following offices:

* Gov/Lt Gov
* Attorney General
* State Auditor
* Secretary of State
* State Treasurer
* U.S. Senate
* U.S. House
* State Senator
* State Representative

Precinct-level results are available for the 2006 general.

**Comment by christopherjenness** [comment]
If no one's working on this, I can do it.

**Comment by christopherjenness** [comment]
Is this completed, or did I miss something?

**Comment by dwillis** [comment]
Looks finished to me. Thanks!
