### ISSUE TITLE
Scrape or convert 2000 county-level U.S. House results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#7]
Using [the data here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/USHouseReps11072000.aspx), produce a CSV file. Things to know:

* Output file is named `20001107__oh__general__house.csv`
* Headers should be: county, candidate, party, office, district, votes, pct. Use `U.S. House` as office and the district number as the district.
* Only include candidate totals, don't include overall totals.

**Comment by ursulakaczmarek** [comment]
sending completed .csv via gmail
