### ISSUE TITLE
Scrape or convert 2000 county-level Ohio Senate results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#8]
Using [the data here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults/OHSenate11072000.aspx), produce a CSV file. Things to know:

* Output file is named `20001107__oh__general__state_senate.csv`
* Headers should be: county, candidate, party, office, district, votes, pct. Use `State Senate` as office and the district number as the district.
* Only include candidate totals, don't include overall totals.

**Comment by ursulakaczmarek** [comment]
sending via gmail
